//! Conformance tests driven by `vectors/pipeline-vectors-v0.2.4.json`.
//!
//! `data/vectors.rs` is GENERATED by `tools/gen_test_vectors.py` from the
//! vector file — do not edit by hand. CI verifies the two stay in sync.

use axonos_pipeline_core::*;

include!("data/vectors.rs");

fn flag_code(f: ArtifactFlag) -> u8 {
    match f {
        ArtifactFlag::Clean => 0,
        ArtifactFlag::AmplitudeExceeded => 1,
        ArtifactFlag::Saturated => 2,
    }
}

fn fixture_frame() -> RawFrame<'static> {
    RawFrame::new(
        FIXTURE_SEQ,
        FIXTURE_TIMESTAMP_US,
        SampleRate::new(FIXTURE_RATE_HZ).unwrap(),
        ChannelMask::from_bits(FIXTURE_CHANNEL_MASK),
        FIXTURE_SAMPLES,
    )
    .unwrap()
}

#[test]
fn fnv_anchors() {
    for (input, want) in FNV_VECTORS {
        assert_eq!(fnv1a_64(input), *want);
    }
}

#[test]
fn fixture_frame_checksum() {
    let frame = fixture_frame();
    assert_eq!(frame.samples_per_channel(), FIXTURE_SAMPLES_PER_CHANNEL);
    assert_eq!(
        frame.channels().enabled_count() as usize,
        FIXTURE_CHANNEL_COUNT
    );
    assert_eq!(frame.checksum(), FIXTURE_FRAME_CHECKSUM);
}

#[test]
fn window_cases() {
    for (n, w, h, want) in WINDOW_CASES {
        assert_eq!(window_count(*n, *w, *h).ok(), *want, "n={n} w={w} h={h}");
    }
}

#[test]
fn epoch_iteration_matches_window_math() {
    let frame = fixture_frame();
    let (w, h) = (EPOCH_CASE_WINDOW, EPOCH_CASE_HOP);
    let want = window_count(frame.samples_per_channel(), w, h).unwrap();
    let iter = frame.epochs(w, h).unwrap();
    assert_eq!(iter.len(), want);
    for (k, epoch) in frame.epochs(w, h).unwrap().enumerate() {
        assert_eq!(epoch.index() as usize, k);
        assert_eq!(epoch.start_t(), k * h);
        assert_eq!(epoch.len_t(), w);
        assert_eq!(epoch.sample(0, 0), frame.sample(k * h, 0));
        assert_eq!(epoch.sample(w, 0), None);
    }
}

#[test]
fn artifact_cases() {
    for (i, (samples, threshold, want)) in ARTIFACT_CASES.iter().enumerate() {
        let got = artifact_scan(samples, *threshold).unwrap();
        assert_eq!(flag_code(got), *want, "artifact case {i}");
    }
}

#[test]
fn artifact_rejects_nonpositive_threshold() {
    assert_eq!(artifact_scan(&[0], 0), Err(PipelineError::InvalidThreshold));
    assert_eq!(
        artifact_scan(&[0], -5),
        Err(PipelineError::InvalidThreshold)
    );
}

#[test]
fn decision_validation() {
    let d = ClassifierDecision::intent(3, 750).unwrap();
    assert_eq!(
        d,
        ClassifierDecision::Intent {
            class: 3,
            confidence_permille: 750
        }
    );
    assert!(!d.is_abstain());
    assert!(ClassifierDecision::NoIntent.is_abstain());
    assert_eq!(
        ClassifierDecision::intent(0, 1001),
        Err(PipelineError::InvalidConfidence)
    );
}

#[test]
fn mask_columns() {
    for (bits, ch, want) in MASK_CASES {
        let mask = ChannelMask::from_bits(*bits);
        assert_eq!(mask.column_of(*ch), *want, "bits={bits:#06x} ch={ch}");
        if let Some(col) = want {
            assert_eq!(mask.channel_at(*col), Some(*ch));
        }
    }
    assert_eq!(ChannelMask::first_n(8).bits(), 0x00FF);
    assert_eq!(ChannelMask::first_n(8).enabled_count(), 8);
}

#[test]
fn frame_validation() {
    let samples = [0i32; 8];
    assert!(matches!(
        RawFrame::new(
            0,
            0,
            SampleRate::HZ_250,
            ChannelMask::from_bits(0),
            &samples
        ),
        Err(PipelineError::EmptyChannelMask)
    ));
    let seven = [0i32; 7];
    assert!(matches!(
        RawFrame::new(0, 0, SampleRate::HZ_250, ChannelMask::first_n(8), &seven),
        Err(PipelineError::SampleLengthMismatch)
    ));
    assert!(SampleRate::new(0).is_none());
}

#[test]
fn debug_redacts_samples() {
    let frame = fixture_frame();
    let rendered = format!("{frame:?}");
    assert!(rendered.contains("<redacted>"));
    assert!(!rendered.contains("samples: ["));
    let first = format!("{}", FIXTURE_SAMPLES[0]);
    assert!(
        !rendered.contains(&first),
        "raw sample value leaked into Debug output"
    );
}

#[test]
fn boundary_accepts_terminal_decision() {
    boundary::assert_boundary_safe(&ClassifierDecision::NoIntent);
}

#[test]
fn dc_remove_cases() {
    for &(input, mean, expected) in DC_CASES {
        let mut out = vec![0i32; input.len()];
        let m = remove_mean(input, &mut out).unwrap();
        assert_eq!(m, mean);
        assert_eq!(out.as_slice(), expected);
    }
}

#[test]
fn fir_cases() {
    for &(input, coeffs, shift, expected) in FIR_CASES {
        let mut out = vec![0i32; input.len()];
        fir(input, coeffs, shift, &mut out).unwrap();
        assert_eq!(out.as_slice(), expected);
    }
}

#[test]
fn dsp_error_paths() {
    let mut out2 = [0i32; 2];
    assert_eq!(remove_mean(&[], &mut out2), Err(PipelineError::EmptyInput));
    assert_eq!(
        remove_mean(&[1, 2, 3], &mut out2),
        Err(PipelineError::OutputLengthMismatch)
    );
    assert_eq!(fir(&[], &[1], 0, &mut out2), Err(PipelineError::EmptyInput));
    assert_eq!(
        fir(&[1, 2], &[], 0, &mut out2),
        Err(PipelineError::EmptyKernel)
    );
    assert_eq!(
        fir(&[1, 2, 3], &[1], 0, &mut out2),
        Err(PipelineError::OutputLengthMismatch)
    );
    assert_eq!(
        fir(&[1, 2], &[1], 32, &mut out2),
        Err(PipelineError::InvalidShift)
    );
}
