// @generated by tools/gen_test_vectors.py from
// vectors/pipeline-vectors-v0.1.0.json — DO NOT EDIT.
// CI re-generates and diffs this file (tools/validate_vectors.py).

const FNV_VECTORS: &[(&[u8], u64)] = &[
    (b"", 0xcbf29ce484222325),
    (b"a", 0xaf63dc4c8601ec8c),
    (b"axonos", 0xc141163b4c93c297),
    (b"AxonOS Signal Pipeline", 0x0d4530917509cb45),
];

const FIXTURE_SEQ: u32 = 7;
const FIXTURE_TIMESTAMP_US: u64 = 1711540800000000;
const FIXTURE_RATE_HZ: u32 = 250;
const FIXTURE_CHANNEL_MASK: u16 = 0x00ff;
const FIXTURE_CHANNEL_COUNT: usize = 8;
const FIXTURE_SAMPLES_PER_CHANNEL: usize = 16;
const FIXTURE_FRAME_CHECKSUM: u64 = 0x875af1b082c94a2d;
const FIXTURE_SAMPLES: &[i32] = &[
    5598, -7640, 2245, 7186, 6691, 3577, -613, 5060, 361, -7167, 2792, -561,
    299, 6005, -5333, -4107, 2477, 4893, -7260, -7094, -2921, 2351, 4946, -945,
    585, 849, 2526, -3040, -5076, -6795, 7914, 3447, 3210, -2747, -2205, 5325,
    7211, 5580, -3821, -3849, -669, 7678, -2712, -4512, -4170, -7104, 7648, -3096,
    -3032, -4528, -3689, 3668, -2761, -4911, 7829, -35, 1107, 824, -3199, -6838,
    -5819, -3968, -5925, -1963, 5305, 1277, 3314, 5586, -5908, -7252, -1584, 1401,
    -5530, -4775, -49, -4509, -2825, 930, -7020, 2274, -5672, 5386, -6300, 1709,
    -3176, -5567, -1654, 6881, -6455, 6384, -7622, -5429, 3889, 3397, -3177, -3255,
    -4450, -4009, -5497, 5696, -7381, -6165, -5175, -1119, -2476, 1331, 6747, 3139,
    5953, 3538, -7332, 2839, -5774, 3046, -5341, 1786, -2025, 3259, 298, -3832,
    -482, -6396, -1511, -7385, 4565, 4391, -390, -1085,
];

const EPOCH_CASE_WINDOW: usize = 4;
const EPOCH_CASE_HOP: usize = 4;

const WINDOW_CASES: &[(usize, usize, usize, Option<usize>)] = &[
    (16usize, 16usize, 1usize, Some(1)),
    (16usize, 8usize, 4usize, Some(3)),
    (16usize, 4usize, 4usize, Some(4)),
    (1000usize, 250usize, 125usize, Some(7)),
    (16usize, 32usize, 8usize, None),
    (16usize, 0usize, 1usize, None),
    (16usize, 4usize, 0usize, None),
];

const ARTIFACT_CASES: &[(&[i32], i32, u8)] = &[
    (&[0, 100, -100, 950], 1000, 0),
    (&[0, 1500, -2, 3], 1000, 1),
    (&[8388607, 0, 1], 1000, 2),
    (&[2000, -8388608], 1000, 2),
    (&[-1001, 0], 1000, 1),
];

const MASK_CASES: &[(u16, u8, Option<usize>)] = &[
    (0x00ff, 0, Some(0)),
    (0x00ff, 7, Some(7)),
    (0x00ff, 8, None),
    (0x00a5, 0, Some(0)),
    (0x00a5, 2, Some(1)),
    (0x00a5, 5, Some(2)),
    (0x00a5, 7, Some(3)),
    (0x00a5, 1, None),
];
